# playbook.yml
---
- name: Configuration commune à toutes les machines
  hosts: all
  become: yes
  roles:
    - base

- name: Déploiement du serveur Redis
  hosts: redis
  become: yes
  roles:
    - redis

- name: Déploiement de la base de données PostgreSQL
  hosts: postgresql
  become: yes
  roles:
    - postgresql

- name: Déploiement du service Poll
  hosts: poll
  become: yes
  roles:
    - poll

- name: Déploiement du service Worker
  hosts: worker
  become: yes
  roles:
    - worker

- name: Déploiement du service Result
  hosts: result
  become: yes
  roles:
    - result