/*
** EPITECH PROJECT, 2026
** camera
** File description:
** camera class for the project bootstrap_raytracer
*/

#pragma once

#include "math.hpp"
#include "ray.hpp"
#include "rectangle.hpp"

namespace RayTracer {

    // Represents a camera in the raytracing scene.
    // The camera defines the viewpoint and the screen onto which rays are cast.
    // Complies with the Coplien form (special member functions).
    class Camera {
        public:
            Math::Point3D origin;
            Rectangle3D screen;

            // Default constructor.
            // Initializes camera origin at (0, 0, 0) with a default screen.
            Camera()
                : origin(0.0, 0.0, 0.0),
                  screen(Math::Point3D(0.0, 0.0, 0.0),
                         Math::Vector3D(1.0, 0.0, 0.0),
                         Math::Vector3D(0.0, 1.0, 0.0))
            {
            }

            // Constructor with custom screen.
            Camera(const Rectangle3D &screenValue)
                : origin(0.0, 0.0, 0.0), screen(screenValue)
            {
            }

            // Copy constructor (implicitly generated by default).
            Camera(const Camera &) = default;

            // Copy assignment operator (implicitly generated by default).
            Camera &operator=(const Camera &) = default;

            // Move constructor (implicitly generated by default).
            Camera(Camera &&) = default;

            // Move assignment operator (implicitly generated by default).
            Camera &operator=(Camera &&) = default;

            // Default destructor.
            ~Camera() = default;

            // Generate a ray for a given pixel position on the screen.
            // Parameters:
            //   u: normalized horizontal coordinate in [0, 1]
            //   v: normalized vertical coordinate in [0, 1]
            // Returns: Ray going from camera origin through the pixel at (u, v)
            Ray ray(double u, double v) const
            {
                Math::Point3D pixelPos = screen.pointAt(u, v);
                Math::Vector3D direction(pixelPos.x - origin.x,
                                         pixelPos.y - origin.y,
                                         pixelPos.z - origin.z);
                return Ray(origin, direction);
            }
    };
} /* namespace RayTracer */
